### PR TITLE
Improve getting gradle version image tag

### PR DESCRIPTION
**Pull request by AnguloHerrera**
@TarodBOFH and I think it's better if we get the gradle version from the .properties file to avoid someone has to update the pipeline file when we upgrade the gradle version.

This branch has been forked from the Juan's PR - https://github.com/returnly/java-code-style/pull/6

### CODE REVIEW

**Comment by TarodBOFH** [comment]
I deleted my pull request. This one has my changes plus the version variable.

**Comment by eric239** [comment]
To be clear, I agree with the intent, but I don't want to ever debug bash code if that can be avoided :-)

**Comment by AnguloHerrera** [comment]
@eric239 it's a good idea, although I don't understand where you say we can run the command `gradle --version`, because `gradle` is installed inside of the docker container, so if I am not wrong, if we want to do it we should do:
- build the docker image on the pipeline and push it to AWS registry to be able to get it in the next step (using the docker buildkite plugin)
- run the command `gradle --version` inside the docker container + commands to parse and export the gradle_version
- build again the docker image with the new tag (adding the gradle_version)
- push the docker image with the gradle tag

Maybe I am wrong and I didn't understand you well, but if not I don't like so much this process because it's very complex and strange.
Let me know if you are thinking in other way and I didn't understand you :) thanks!!

**Comment by TarodBOFH** [comment]
@eric239 it is more complicated than that. This doesn't use `common-gradle-scripts` at all (it is producing the image that those scripts will use) and there are no intermediate steps to play with.

I reopened https://github.com/returnly/java-code-style/pull/8 with an env variable and we'll just need to remember to update it.

@AnguloHerrera as discussed, you can dismiss this PR if you want.

**Comment by AnguloHerrera** [comment]
Yes, I am going to close this PR, so let's review the new PR. Thanks @TarodBOFH

**Pull request closed without merging**
